
GET http://qebui.js-soft.local:8000/sap/opu/odata/JSS/TBUSINESSOBJECT_CDS/$metadata HTTP/1.1
content-type: application/json

###

GET http://qebui.js-soft.local:8000/sap/opu/odata/JSS/TBUSINESSOBJECT_CDS/xJSSxTBUSINESSOBJECT?$format=json HTTP/1.1
content-type: application/json

###
